# Generated by Django 2.2.5 on 2019-09-23 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('OriginalTodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todomodel',
            name='priority',
            field=models.CharField(choices=[('warning', 'high'), ('success', 'normal'), ('primary', 'low')], default='warning', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
